export const config = {
    RPC_URL: 'http://143.244.131.28:26657',
    REST_URL: 'http://143.244.131.28:1317',
    EXPLORER_URL: 'https://explorer.evmos.org',
    NETWORK_NAME: 'Evmos Olympus Mons ',
    NETWORK_TYPE: 'testnet',
    CHAIN_ID: 'evmos_9000-2',
    CHAIN_NAME: 'Evmos',
    COIN_DENOM: 'PHOTON',
    COIN_MINIMAL_DENOM: 'aphoton',
    COIN_DECIMALS: 18,
    PREFIX: 'evmos',
    COIN_TYPE: 118,
    COINGECKO_ID: 'evmos',
    DEFAULT_GAS: 250000,
    GAS_PRICE_STEP_LOW: 0.005,
    GAS_PRICE_STEP_AVERAGE: 0.025,
    GAS_PRICE_STEP_HIGH: 0.08,
    FEATURES: ['stargate', 'ibc-transfer'],
};
